<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE document PUBLIC "+//IDN docutils.sourceforge.net//DTD Docutils Generic//EN//XML" "http://docutils.sourceforge.net/docs/ref/docutils.dtd">
<!-- Generated by Docutils 0.16 -->
<document source="C:\Users\penci\OneDrive\Desktop\LibPyMath\LibPyMath\docs\source\libpymath.src.error.rst">
    <section ids="libpymath-src-error-package" names="libpymath.src.error\ package">
        <title>libpymath.src.error package</title>
        <section ids="module-libpymath.src.error module-contents" names="module\ contents">
            <title>Module contents</title>
            <index entries="['pair',\ 'module;\ libpymath.src.error',\ 'module-libpymath.src.error',\ '',\ None]"></index>
        </section>
    </section>
</document>
